services:
  app-prod:
    container_name: qual-backend-prod
    build:
      dockerfile: ./Dockerfile.prod
      context: .
    volumes:
      - type: volume
        source: gunicorn
        target: /tmp/gunicorn
    command: gunicorn qual.wsgi --bind=unix:/tmp/gunicorn/gunicorn.sock

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.nginx
    depends_on:
      - app-prod
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: gunicorn
        target: /tmp/gunicorn

volumes:
  gunicorn: