FROM python:3.12.3-slim-bullseye

RUN apt update && \
    apt install -y --no-install-recommends \ 
    g++ make cmake \
    libboost-dev git
    
RUN mkdir -p /home/app

WORKDIR /home/app

COPY requirements.txt /home/app/requirements.txt

RUN pip install -r requirements.txt

COPY . /home/app