version: '3.9'

services:
  app:
    container_name: qual-backend
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - "18000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000