# Generated by Django 5.0.6 on 2024-05-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('word_to_type', models.CharField(max_length=100)),
                ('key_pressed', models.CharField(max_length=1)),
                ('correct', models.BooleanField()),
            ],
        ),
    ]
