# Generated by Django 5.0.6 on 2024-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_type_gamelog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='correct',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='key_pressed',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='word_to_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
